stages:
  - build
  - test

variables:
    BUILD_DIR: "gitlab_build"
    GTEST_COLOR: "1"
    DO_BUILD: "yes"
    DO_TEST: "yes"
    METALL_TEST_DIR: "/l/ssd/"
    IMG: ""

default:
  before_script:
    - echo "=== before_script section ==="
    - hostname
    - spack find
    - spack clean
    - spack install gcc@9.2.0
#    - spack install gcc@9.1.0
#    - spack install gcc@8.3.0
#    - spack install gcc@8.2.0
#    - spack install gcc@8.1.0

  after_script:
    - echo "=== after_script section ==="

.build:
  stage: build
  tags:
    - catalyst
    - shell
  script:
    - echo "=== build section ==="
    - for b in {64..70}; do export BOOST_VERSION=${b}; bash ./scripts/CI/download_boost.sh; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh; done

build_gcc9.2:
  extends: .build
  script:
    - spack load gcc@9.2.0

# build_gcc9.1:
#   extends: .build
#   script:
#     - spack load gcc@9.1.0

# build_gcc8.3:
#   extends: .build
#   script:
#     - spack load gcc@8.3.0

# build_gcc8.2:
#   extends: .build
#   script:
#     - spack load gcc@8.2.0

# build_gcc8.1:
#   extends: .build
#   script:
#     - spack load gcc@8.1.0
