stages:
  - build
  - test

variables:
    GTEST_COLOR: "1"
    METALL_TEST_DIR: "/l/ssd/"
    BOOST_INSTALL_ARGS: "~atomic ~chrono ~clanglibcpp ~context ~coroutine ~date_time ~debug ~exception ~fiber ~filesystem ~graph ~icu ~iostreams ~locale ~log ~math ~mpi ~multithreaded ~numpy ~pic ~program_options ~python ~random ~regex ~serialization ~shared ~signals ~singlethreaded ~system ~taggedlayout ~test ~thread ~timer ~versionedlayout ~wave"

default:
  before_script:
    - echo "=== before_script section ==="
    - hostname
    - pwd
    - spack find
    - spack clean
#    - spack install gcc@9.2.0
#    - spack install gcc@9.1.0
#    - spack install gcc@8.3.0
    - spack install gcc@8.2.0
#    - spack install gcc@8.1.0
    - spack install boost@1.72.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.71.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.70.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.69.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.68.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.67.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.66.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.65.1 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.65.0 ${BOOST_INSTALL_ARGS}
#    - spack install boost@1.64.0 ${BOOST_INSTALL_ARGS}
    - spack find 
  after_script:
    - echo "=== after_script section ==="

.build:
  stage: build
  tags:
    - catalyst
    - slurm
  script:
    - echo "=== build section ==="
    - spack load boost@1.72.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/lc_gitlab/build.sh
#    - spack load boost@1.71.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.70.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.69.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.68.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.67.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.66.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.65.1; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.65.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh
#    - spack load boost@1.64.0; salloc -N1 -t 2-00:00 --clear-ssd bash ./scripts/CI/build_and_test.sh

#build_gcc9.2:
#  extends: .build
#  script:
#    - spack load gcc@9.2.0

# build_gcc9.1:
#   extends: .build
#   script:
#     - spack load gcc@9.1.0

# build_gcc8.3:
#   extends: .build
#   script:
#     - spack load gcc@8.3.0

# build_gcc8.2:
#   extends: .build
#   script:
#    - spack load gcc@8.2.0

 build_gcc8.1:
   extends: .build
   script:
#     - spack load gcc@8.1.0
     - module load gcc/8.1.0
