services: docker
dist: trusty
language: cpp

env:
  matrix:
  - BOOST_VERSION=1_72_0 GCC_VER=8.1.0
  - BOOST_VERSION=1_72_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_72_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_72_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_72_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_71_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_71_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_71_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_71_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_71_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_70_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_70_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_70_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_70_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_70_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_69_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_69_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_69_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_69_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_69_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_68_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_68_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_68_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_68_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_68_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_67_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_67_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_67_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_67_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_67_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_66_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_66_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_66_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_66_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_66_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_65_1 GCC_VER=8.1.0
#  - BOOST_VERSION=1_65_1 GCC_VER=8.2.0
#  - BOOST_VERSION=1_65_1 GCC_VER=8.3.0
#  - BOOST_VERSION=1_65_1 GCC_VER=9.1.0
#  - BOOST_VERSION=1_65_1 GCC_VER=9.2.0
#  - BOOST_VERSION=1_65_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_65_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_65_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_65_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_65_0 GCC_VER=9.2.0
#  - BOOST_VERSION=1_64_0 GCC_VER=8.1.0
#  - BOOST_VERSION=1_64_0 GCC_VER=8.2.0
#  - BOOST_VERSION=1_64_0 GCC_VER=8.3.0
#  - BOOST_VERSION=1_64_0 GCC_VER=9.1.0
#  - BOOST_VERSION=1_64_0 GCC_VER=9.2.0

script:
  - docker run --rm  kiwabuchi/metall_test:centos7 -e CC=gcc${GCC_VER} -e CXX=g++${GCC_VER} -e CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:/var/boost/boost_${BOOST_VERSION}" bash ./scripts/CI/travis_ci/build_and_test.sh
