
site_name: Metall
site_author: 'Keita Iwabuchi (LLNL), Roger A Pearce (LLNL), and Maya B Gokhale (LLNL)'
copyright: Copyright 2020 Lawrence Livermore National Security, LLC

docs_dir: 'docs/readthedocs'
theme: 'readthedocs'
extra_css:
  - ./css/custom.css

repo_url: https://github.com/LLNL/metall
edit_uri: 'tree/develop/docs/readthedocs'

nav:
- Home: 'index.md'
- 'Getting Started': 'getting_started.md'
- 'Example': 'example.md'
- 'Advanced':
  - 'Build Example, Test, and Benchmark': 'advanced/build_sources.md'
  - 'Use Umap': 'advanced/umap.md'
- 'Publication': 'publication.md'
- 'About': 'about.md'
