
site_name: Metall
site_author: 'Keita Iwabuchi (LLNL)'
copyright: Copyright 2020 Lawrence Livermore National Security, LLC

docs_dir: 'docs/readthedocs'
theme: 'readthedocs'

repo_url: https://github.com/LLNL/metall
edit_uri: 'tree/develop/docs/readthedocs'

nav:
- Home: 'index.md'
- 'Getting Started': 'getting_started.md'
- 'Publication': 'publication.md'
- About:
    - 'Authors': 'authors.md'
    - 'License': 'license.md'
    - 'Release': 'release.md'
#    - 'Release Notes': 'release-notes.md'